name: Clarence Stock Market Report v2

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  report:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Report
        shell: pwsh
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMS_TO: ${{ secrets.SMS_TO }}
        run: |
          ./scripts/Get-Stocks.ps1

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: stock-report
          path: MarketReport.txt
